version: '3'
services:
  app1:
    container_name: app1
    image: myapp
  app2:
    container_name: app2
    image: myapp
  app3:
    container_name: app3
    image: myapp
  app4:
    container_name: app4
    image: myapp
  nginx:
    image: nginx:alpine
    build:
      context: ./proxy
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"